# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NRTLocationSharing' do
	pod 'MQTTClient'
	pod 'AFNetworking'
	pod 'BMKLocationKit'
	pod 'BaiduMapKit'
end
